
const API_CONFIG = {
  API_KEY: process.env.REACT_APP_API_KEY,
  EMPLOYEE_URL: process.env.REACT_APP_EMPLOYEE_API_URL,
  STUDENT_URL: process.env.REACT_APP_STUDENT_API_URL,
  DEPARTMENT_URL: process.env.REACT_APP_DEPARTMENT_API_URL,
  AUTH_LOGIN_URL: process.env.REACT_APP_AUTH_LOGIN_URL,
  USERS_URL: process.env.REACT_APP_USERS_API_URL,
  ROLES_URL:process.env.REACT_APP_ROLES_API_URL
};

export default API_CONFIG;